### PR TITLE
support custom variables

### PR DESCRIPTION
**Pull request by mtwtfss**

### CODE REVIEW

**Comment by concon121** [comment]
Looks good, please can you update the readme with documentation and example usage?

**Comment by mtwtfss** [comment]
Thanks @concon121, I've added an example to the readme

**Comment by mtwtfss** [comment]
Hi @concon121 👋 Can we merge this now?

**Comment by concon121** [comment]
Changes will be available in version 0.1.0
https://www.npmjs.com/package/serverless-aws-resource-names/v/0.1.0
Thanks for your contribution!

**Pull request merged**
